{
 "title": "Trends V2",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Helpful metrics to visualize Trends Dashboard:\n\n- [Container Metrics](https://grafana.gopala.duckdns.org/d/4dMaCsRZz/docker-container-and-host-metrics?var-interval=30s&orgId=1&timezone=browser&var-job=cadvisor&var-node=cadvisor&var-port=8080&refresh=10s&from=$__from&to=$__to&var-container=trends)\n- [Node Metrics](https://grafana.gopala.duckdns.org/d/rYdddlPWk/node-exporter-full?orgId=1&from=$__from&to=$__to&timezone=browser&var-datasource=default&var-job=node-exporter&var-node=node-exporter:9100&var-diskdevices=%5Ba-z%5D%2B%7Cnvme%5B0-9%5D%2Bn%5B0-9%5D%2B%7Cmmcblk%5B0-9%5D%2B&refresh=1m)"
   }
  },
  {
   "title": "Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true
  },
  { "title": "Trends API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Init Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ticker_init_latency{quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "Get Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ticker_get_latency{quantile=\"0.99\"}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Ticker Update Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ticker_update_latency{quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "Save Data Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "db_save_ticker_latency{quantile=\"0.99\"}"
    }
   ]
  }
 ]
}