networks:
  gluetun-network:
    ipam:
      config:
        - subnet: 172.24.0.0/24
    name: gluetun-network
services:
  qbittorrent:
    profiles: ["arr", "common"]
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=Asia/Kolkata
      - TORRENTING_PORT=${TORRENTING_PORT}
    volumes:
      - ${CONFIG}:/config
      - ${DOWNLOADS}:/downloads
    security_opt:
      - no-new-privileges:true
    ports:
      - 8081:8080
    networks:
      gluetun-network:
        ipv4_address: 172.24.0.3
    restart: unless-stopped
  gluetun:
    profiles: ["arr", "common"]
    image: qmcgaw/gluetun
    container_name: gluetun
    networks:
      gluetun-network:
        ipv4_address: 172.24.0.2
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${WIREGUARD_CONFIG}:/gluetun/wireguard/wg0.conf
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
    ports:
      - "${PROWLARR_PORT:-9696}:9696"
      - "${RADARR_PORT:-7878}:7878"
      - "${SONARR_PORT:-8989}:8989"
      - "${FALREAOLVERR_PORT:-8191}:8191"
  prowlarr:
    profiles: ["arr", "common"]
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ${PROWLARR_CONFIG}:/config
    network_mode: "container:gluetun"
    restart: unless-stopped
  radarr:
    profiles: ["arr", "common"]
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ${RADARR_CONFIG}:/config
      - ${RADARR_DATA}:/movies
      - ${EXTERNAL_DRIVE_2}:/media/hdd2
      - ${EXTERNAL_DRIVE_3}:/media/hdd3
      - ${TORRENT_DOWNLOADS}:/downloads
    network_mode: "container:gluetun"
    restart: unless-stopped
  sonarr:
    profiles: ["arr", "common"]
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ${SONARR_CONFIG}:/config
      - ${SONARR_DATA}:/shows
      - ${EXTERNAL_DRIVE_2}:/media/hdd2
      - ${EXTERNAL_DRIVE_3}:/media/hdd3
      - ${TORRENT_DOWNLOADS}:/downloads
    network_mode: "container:gluetun"
    restart: unless-stopped
  bazarr:
    profiles: ["arr", "common"]
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${BAZARR_CONFIG}:/config
      - ${EXTERNAL_DRIVE_2}:/media/hdd2
      - ${EXTERNAL_DRIVE_3}:/media/hdd3
    ports:
      - 6767:6767
    networks:
      - gluetun-network
    restart: unless-stopped
