services:
  firefox:
    profiles: ["firefox"]
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=Asia/Kolkata
      - FIREFOX_CLI=https://www.linuxserver.io/ #optional
    volumes:
      - ${FIREFOX_CONFIG}:/config
    ports:
      - 3002:3000
      - 3003:3001
    shm_size: "1gb"
    restart: unless-stopped
