services:
  homepage:
    profiles: ["home"]
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: ${PUID}
      PGID: ${GUID}
    ports:
      - 3001:3000
    volumes:
      - ${HOMEPAGE_CONFIG}:/app/config
      - ${EXTERNAL_DRIVE_1}:/disk0
      - ${EXTERNAL_DRIVE_2}:/disk1
      - ${EXTERNAL_DRIVE_3}:/disk2
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
