services:
  nginx:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
    profiles: ["common", "minimal"]
    container_name: nginx
    image: ${NGINX_IMAGE}
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${NGINX_DATA}:/data
      - ${NGINX_LESTENCRYPT}:/etc/letsencrypt
